show unsupported version; Print routine should return string

diff --git a/version/generate_version b/version/generate_version
--- a/version/generate_version
+++ b/version/generate_version
@@ -17,9 +17,26 @@ else
   useDefaultVersionString="True"
 fi
 
-GitCommitStr=`git show | grep commit | cut -f 2 -d ' ' | cut -b 1-10`
-VersionStr=`cat CURRENT_VERSION`
-BuildTimeStr=`date`
+# GitCommitStr=`git show | grep commit | cut -f 2 -d ' ' | cut -b 1-10`
+# VersionStr=`cat CURRENT_VERSION`
+# BuildTimeStr=`date`
+
+# borrow this logic from docker (https://github.com/docker/docker/blob/master/hack/make.sh)
+VersionStr=$(< ./CURRENT_VERSION)
+if command -v git &> /dev/null && git rev-parse &> /dev/null; then
+  GitCommitStr=$(git rev-parse --short HEAD)
+  if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
+    GitCommitStr="$GitCommitStr-unsupported"
+  fi
+  ! BuildTimeStr=$(date --rfc-3339 ns | sed -e 's/ /T/') &> /dev/null
+  if [ -z $BuildTimeStr ]; then
+    # If using bash 3.1 which doesn't support --rfc-3389, eg Windows CI
+    BuildTimeStr=$(date -u)
+  fi
+else
+  echo >&2 'error: unable to determine the git revision'
+  exit 1
+fi
 
 cat > $file_name << EOF
 $UseVersionStr
