Move to go1.6 vendoring

diff --git a/vendor/github.com/contiv/objdb/checks b/vendor/github.com/contiv/objdb/checks
--- a/vendor/github.com/contiv/objdb/checks
+++ b/vendor/github.com/contiv/objdb/checks
@@ -11,19 +11,10 @@ fi
 
 BUILD_PKGS=$1
 
-echo "+++ checking packages " $BUILD_PKGS
-echo "+++ Checking Go version..."
-ver=$(go version | awk '{print $3}')
-minVer="go1.5.1"
-maxVer="go1.6.2"
-if [[ ${ver} < ${minVer} ]]; then
-    echo "!!! Go version check failed. Expected >=${minVer} but found ${ver}"
-    exit 1
-fi
-
-if [[ ${ver} > ${maxVer} ]]; then
-    echo "!!! Go version check failed. Expected =<${maxVer} but found ${ver}"
-    exit 1
+if ! go get github.com/golang/lint/golint
+then
+  echo "!!! Could not install golint"
+  exit 1
 fi
 
 echo "+++ Checking gofmt..."
