scripts/checks: adjust to ensure go 1.4.2 is in use
Signed-off-by: Erik Hollensbe <erik+github@hollensbe.org>

diff --git a/scripts/checks b/scripts/checks
--- a/scripts/checks
+++ b/scripts/checks
@@ -13,9 +13,15 @@ BUILD_PKGS=$1
 
 echo "+++ Checking Go version..."
 ver=$(go version | awk '{print $3}')
-minVer="go1.4"
+minVer="go1.4.2"
+maxVer="go1.4.2"
 if [[ ${ver} < ${minVer} ]]; then
     echo "!!! Go version check failed. Expected >=${minVer} but found ${ver}"
+    exit 1
+fi
+
+if [[ ${ver} > ${maxVer} ]]; then
+    echo "!!! Go version check failed. Expected =<${maxVer} but found ${ver}"
     exit 1
 fi
 
