Some fixups to lint and the checks script based on @mapuri's comments

diff --git a/scripts/checks b/scripts/checks
--- a/scripts/checks
+++ b/scripts/checks
@@ -29,14 +29,15 @@ fi
 echo "+++ golint tree..."
 for i in $(find . -maxdepth 1 -type d -name '*' | grep -vE '/\..*$')
 do
-  output=$(golint "${i}") # golint has no exit codes
-  if [ -n "${output}" ]
-  then
-    echo -e "!!! golint checking failed: "
-    echo -n "${output}"
-    exit 1
-  fi
+  output="${output}$(golint ${i})" # golint has no exit codes
 done
+
+if [ -n "${output}" ]
+then
+  echo -e "!!! golint checking failed: "
+  echo -n "${output}"
+  exit 1
+fi
 
 echo "+++ go vet tree..."
 for i in ${BUILD_PKGS}
