Add system tests, that allow to ensure basic sanity of netplugin - system-tests are:   - regular 'go test'   - built and run in a sandboxed (vagrant) environment using 'make system-test' - Added the first system-test to verify ping between containers in a single host,   single vlan environment - Integrated demo environment with Makefile. A demo environment can   be launched using 'make demo' (instead of vagrant up) - Changed Vagrantfile a bit to mount the host's GOBIN directory to access the built   binaries. The Vagrant vms still have readonly access to the project directory but   can no longer build their own binary. This streamlines the build process a bit   and keeps all VMs in cluster synced to common set of binaries. - Fix the Makefile to allow non-root user to do a build - Added build time checks for go-version, fo-fmt etc - Updated VagrantFile to use a custom vagrant-box with pre-installed binaries. The box is   right now hosted in cisco.com domain which limits it public acess (need to change) - Update Readme.md with built, test and demo intructions

diff --git a/scripts/cleanup b/scripts/cleanup
--- a/scripts/cleanup
+++ b/scripts/cleanup
@@ -6,6 +6,14 @@
 # allow easy experimentation on failure runs or crashes that leaves
 # system in invalid state 
 
+# Note: issuing ovs-vsctl needs 'root' permission otherwise
+# cleanup will silently fail. Make sure the caller invokes this script
+# as 'root' or 'sudo'.
+if [ "$(id -u)" != "0" ]; then
+    echo "Please run as root:$(id -u):"
+    exit 1
+fi
+
 if ! $(which etcdctl > /dev/null 2>&1)
 then
     echo "etcdctl not found !\n"
@@ -21,4 +29,5 @@ fi
 etcdctl rm -recursive /contiv > /dev/null 2>&1
 ovs-vsctl del-br contivBridge > /dev/null 2>&1
 
-# ip link delete portx
+echo "cleanup complete!"
+exit 0
